steps:
  # Step 1: Install dependencies and build the React app
  - name: 'node:18'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install
        npm run build

  # Step 2: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'gcr.io/$PROJECT_ID/react-app-with-dynatrace'
      - '--build-arg'
      - 'ONEAGENT_INSTALLER_SCRIPT_URL=${_ONEAGENT_INSTALLER_SCRIPT_URL}'
      - '--build-arg'
      - 'ONEAGENT_INSTALLER_DOWNLOAD_TOKEN=${_ONEAGENT_INSTALLER_DOWNLOAD_TOKEN}'
      - '.'

  # Step 3: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'gcr.io/$PROJECT_ID/react-app-with-dynatrace'

images:
  - 'gcr.io/$PROJECT_ID/react-app-with-dynatrace'

logsBucket: gs://logs.googleapis.com/cloudbuild